---
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create release
        run: |
          zip -r MailChimp.zip MailChimp
          gh release create v$GITHUB_RUN_NUMBER 'MailChimp.zip'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
